name: auto-approver
run-name: CI for approving PR 

on:
  push:
    branches:
      - "renovate/**"

jobs:
  autoapprove:
    uses: canonical/identity-team/.github/workflows/pr-auto-approval.yaml@7ec3565943646a4abe70497e354edac4357349a8 # v1.9.3
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}