name: auto-approver
run-name: CI for approving PR 

on:
  push:
    branches:
      - "renovate/**"

jobs:
  autoapprove:
    uses: canonical/identity-team/.github/workflows/pr-auto-approval.yaml@d64b860c8679d3539f5f35f3d2494c419d8e41b5 # v1.12.2
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}