name: auto-approver
run-name: CI for approving PR 

on:
  push:
    branches:
      - "renovate/**"

jobs:
  autoapprove:
    uses: canonical/identity-team/.github/workflows/pr-auto-approval.yaml@b5428d226e364de1c5ad601c1ec27c333f489d1d # v1.16.2
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}