name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: canonical/craft-actions/rockcraft-pack@main
        id: rockcraft

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Create SBOM
        run: syft ${{ steps.rockcraft.outputs.rock }} -o spdx-json=kratos.sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          name: kratos-sbom
          path: "kratos.sbom.json"

      - uses: actions/upload-artifact@v3
        with:
          name: rock
          path: ${{ steps.rockcraft.outputs.rock }}
